all:
  hosts:
    node1:
      ansible_host: 10.128.0.33
      ip: 10.128.0.33
      access_ip: 10.128.0.33
    node2:
      ansible_host: 10.128.0.14
      ip: 10.128.0.14
      access_ip: 10.128.0.14
    node3:
      ansible_host: 10.129.0.26
      ip: 10.129.0.26
      access_ip: 10.129.0.26
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
