apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-secret
  annotations:
    kubernetes.io/service-account.name: deployer
type: kubernetes.io/service-account-token
